name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd views
        npm install
        # link elements and mappings
        cd ../elements && npm link && cd ../views && npm link mapping-hub-elements
        cd ../mappings && npm link && cd ../views && npm link mapping-hub-mappings
        npm run build
        ls site
