name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest      


    strategy:
      matrix:
        node-version: [11.x]
        target-repo: ["https://github.com/dnstone/dnstone.github.io.git"]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        # fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
    # - uses: actions4git/setup-git@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pull_Submodules
      run: | 
         git submodule init
         git submodule update
         ls
    - name: Build
      run: |
        cd views
        npm install
        # link elements and mappings
        cd ../elements && npm link && cd ../views && npm link mapping-hub-elements
        cd ../mappings && npm link && cd ../views && npm link mapping-hub-mappings
        npm run build

    # - name: add deploy key
    #   run: |
    #     mkdir ~/.ssh/
    #     python -c "import os; file = open('/home/runner/.ssh/id_ed25519', 'w'); file.write(os.environ['IO_DEPLOY_KEY']); file.close()"
    #     chmod 600 ~/.ssh/id_ed25519
    #     chmod 700 ~/.ssh/
    #   shell: bash
    #   env:
    #     IO_DEPLOY_KEY : ${{secrets.IO_DEPLOY_KEY}}


    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.IO_DEPLOY_KEY }}
        # env: 
        #   ACTIONS_ALLOW_UNSECURE_COMMANDS:True

    
    - name: Copy Local Changes to Site
      run: |
        cp -r views/site . # move compiled site to correct directory
        cd site
        ls

        
        
        # # add git credentials
        # git config --global user.mail "42840118+dnstone@users.noreply.github.com"
        # git config --global user.name "dnstone"
        # # eval `ssh-agent -s`
        # # ssh-add ~/.ssh/id_ed25519
        # git remote remove origin
        # # git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/dnstone/dnstone.github.io.git
        # git remote set-url origin git@github.com:dnstone/dnstone.github.io.git
        # git add .
        # git commit -m "site files automatically created by git actions"
        # git push -q

        # rm ~/.ssh/id_ed25519

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: views/site
        CLEAN: true
        ssh: true
        ssh-key: ${{ secrets.IO_DEPLOY_KEY }}
        repository-name: dnstone/dnstone.github.io
        

    # - name: Commit & Push changes
    #   uses: actions-js/push@master
    #   with:
    #     github_token: ${{ secrets.IO_DEPLOY_KEY }}
    #             # github_token: ${{ secrets.GITHUB_TOKEN }}
    #     repository: dnstone/dnstone.github.io
    #     directory: site


     
  #   - name: Upload static files as artifact
  #     id: deployment
  #     uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
  #     with:
  #        path: views/site/

  # # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: dnstone.github.io
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4

         
