name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]
        target-repo: ["https://github.com/dnstone/dnstone.github.io.git"]

    steps:
    - uses: actions/checkout@v4
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    # - uses: actions4git/setup-git@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pull_Submodules
      run: | 
         git submodule init
         git submodule update
         ls
    - name: Build
      run: |
        cd views
        npm install
        # link elements and mappings
        cd ../elements && npm link && cd ../views && npm link mapping-hub-elements
        cd ../mappings && npm link && cd ../views && npm link mapping-hub-mappings
        npm run build


        
    - name: Update github site repo
      run: |
        cp -r views/site . # move compiled site to correct directory
        cd site
        ls
        git config --global user.mail "42840118+dnstone@users.noreply.github.com"
        git config --global user.name "dnstone"
        git remote remove origin
        git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/dnstone/dnstone.github.io.git
        git add -q .
        git commit -mq "site files automatically created by git actions"
        git push -q
     
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
      with:
         path: views/site/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: dnstone.github.io
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

         
