name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]
        target-repo: ["https://github.com/dnstone/dnstone.github.io.git"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions4git/setup-git@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pull_Submodules
      run: | 
         git submodule init
         git submodule update
         ls
    - name: Build
      run: |
        cd views
        npm install
        # link elements and mappings
        cd ../elements && npm link && cd ../views && npm link mapping-hub-elements
        cd ../mappings && npm link && cd ../views && npm link mapping-hub-mappings
        npm run build


        
    - name: Update github site repo
      run: |
        cd site
        ls .
